In [112]:
import numpy as np

# 🧠 NumPy Practice & Interview Questions (15 Qs)
# 🟩 Basic (1–5)

1. Create an array of numbers from 0 to 9 using NumPy.

2. Create a 3×3 array of all ones.

3. Generate a 3×3 identity matrix.

4. Create an array from 10 to 50 (inclusive) with a step of 5.

5. Generate 5 random integers between 0 and 100.

In [118]:
print( np.arange(10) )

print( 'Next Answer is 2' )
print(np.ones((3,3)))

print( 'Next Answer is 3' )
print( np.eye(3))

print( 'Next Answer is 4' )
print( np.arange(10,55,5) )

print( 'Next Answer is 5' )
print( np.random.randint(0,100,5) )



[0 1 2 3 4 5 6 7 8 9]
Next Answer is 2
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Next Answer is 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Next Answer is 4
[10 15 20 25 30 35 40 45 50]
Next Answer is 5
[67 57 10 65  0]


## 🟨 NumPy Intermediate Practice (Questions 6–10)

6.  Given `arr = np.array([10, 20, 30, 40, 50])`, extract the **first 3 elements** using slicing.

7.  Create a 3×3 array and find:
- The **mean**
- The **maximum**
- The **minimum**

8. Given `arr = np.array([[1, 2], [3, 4], [5, 6]])`, reshape it into a **2×3** array.

9. Generate an array of 10 random numbers and find the **indices of the minimum and maximum values**.

10. Create an array of 10 random integers and replace all values **greater than 50 with 50**.


In [138]:
arr = np.array([10, 20, 30, 40, 50])
print( arr[:3] )

random_array = np.random.randint(0,100,(3,3))
print(f'random array = {random_array}')
print( 'Next Answer is 7' )
print( np.mean(random_array) )
print( np.max(random_array) )
print( np.min(random_array) )

print( 'Next Answer is 8' )
arr = np.array([[1, 2], [3, 4], [5, 6]])
print( arr.reshape(2,3) )

print( 'Next Answer is 9' )
random_array = np.random.randint(0,100,10)
print(f'random array = {random_array}')
print( random_array.argmax() )
print( np.argmin(random_array) )

print( 'Next Answer is 10' )

print( random_array[ random_array>50 ] )
random_array[ random_array>50 ] = 50
print(random_array)

[10 20 30]
random array = [[32  3 89]
 [86 89 71]
 [78 39 39]]
Next Answer is 7
58.44444444444444
89
3
Next Answer is 8
[[1 2 3]
 [4 5 6]]
Next Answer is 9
random array = [80 72 55 44 46 17 68 78 23 41]
0
5
Next Answer is 10
[80 72 55 68 78]
[50 50 50 44 46 17 50 50 23 41]


## 🟩 NumPy Advanced Practice (Questions 11–15)

11.  **Broadcasting Practice**  
Create two arrays:  
`a = np.array([1,2,3])`  
`b = np.array([4])`  
Add them using broadcasting.

12. **Boolean Masking**  
Given `arr = np.array([5,10,15,20,25])`, select all elements greater than 10.

13.  **Matrix Multiplication**  
Create two 3×3 matrices and perform matrix multiplication.

14.  **Random Array Manipulation**  
Create a 4×4 random matrix and:  
- Find its **sum** and **mean**  
- Flatten it into a **1D array**

15. **Unique and Count**  
Given `arr = np.array([1,2,2,3,4,4,4,5])`, find all **unique values** and their **counts**.


In [150]:
a = np.array([1,2,3])
b = np.array([4])
print( a+ b)
print( 'Next Answer is 12' )

arr = np.array([5,10,15,20,25])
print( arr[ arr> 10 ] )

print( 'Next Answer is 13' )
a= np.random.randint(1,10,(3,3))
b= np.random.randint(1,10,(3,3))
print(a@b)
print(a*b)

print( 'Next Answer is 14' )
a= np.random.randint(1,10,(4,4))
print(f' sum = {a.sum()} and mean = {a.mean()} and flatten = {a.flatten()}')

print( 'Next Answer is 15' )
arr = np.array([1,2,2,3,4,4,4,5])
# print(f' unique = {np.unique(arr)} and sum = {np.unique(arr).sum()} ')
values, counts = np.unique(arr, return_counts=True)
print(values, counts)

[5 6 7]
Next Answer is 12
[15 20 25]
Next Answer is 13
[[104 102 131]
 [103 110 155]
 [116 110 138]]
[[42 42 42]
 [72 24 40]
 [ 9 24 45]]
Next Answer is 14
 sum = 73 and mean = 4.5625 and flatten = [9 2 7 1 7 2 6 3 6 3 3 3 1 7 5 8]
Next Answer is 15
[1 2 3 4 5] [1 2 1 3 1]
