In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_new_list = [ [1,2,3], [4,5,6], [7,8,9] ]
print(my_new_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [5]:
np.array(my_new_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
list(range(10)) #-> easy way to create array

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [27]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.random.rand(5)

array([0.1881581 , 0.15972307, 0.26843077, 0.39033703, 0.56384394])

In [30]:
np.random.rand(5,5)

array([[0.30102819, 0.23698834, 0.92607947, 0.69652049, 0.06609215],
       [0.87362666, 0.62527319, 0.18447373, 0.60217492, 0.13970603],
       [0.44876346, 0.16039633, 0.33618143, 0.79251137, 0.83199307],
       [0.49620955, 0.18881431, 0.9554592 , 0.24746909, 0.88706016],
       [0.94283547, 0.68070798, 0.10001724, 0.60390764, 0.47093166]])

In [31]:
np.random.randn(5)

array([-0.4651563 , -1.67433017, -1.73459667, -1.857151  , -0.68717088])

In [32]:
np.random.randn(2,3)

array([[-1.68840473, -0.2459966 ,  0.32336843],
       [ 1.42805766,  2.16645602, -0.81142609]])

In [33]:
np.random.randint(1,100)

17

In [34]:
np.random.randint(1,100,10)

array([96,  1, 77, 40, 25, 22, 45, 17, 11,  3])

In [42]:
arr = np.arange(25)
random_arr = np.random.randint(1,100,10)

In [43]:
print(arr)
print(random_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[66 71 35 70 77 14 22 49 22 96]


In [44]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
print(random_arr.max())
print(random_arr.min())

96
14


In [49]:
print(random_arr.argmax())
print(random_arr.argmin())

9
5


In [50]:
arr.shape

(25,)

In [54]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [55]:
arr.dtype

dtype('int64')

# 2nd part

In [60]:
array = np.arange(0,11)

arr_slice = array[0:5]

In [61]:
arr_slice

array([0, 1, 2, 3, 4])

In [65]:
arr_slice[:] = 100
print(arr_slice)
print(array)

[100 100 100 100 100]
[100 100 100 100 100   5   6   7   8   9  10]


In [66]:
array = np.arange(0, 11)

# Create a copy of the slice
arr_slice = array[0:5].copy()

# The changes will now only affect arr_slice
arr_slice[:] = 100

print(arr_slice)
print(array)

[100 100 100 100 100]
[ 0  1  2  3  4  5  6  7  8  9 10]
